image: sd/sdquadx-build #gcc, cmake, eigen, qpOASES, eiquadprog, cpplint, cppcheck

variables:
  CMAKE_BUILD: /build

cache:
  paths:
    - "$CMAKE_BUILD"

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  # before_script:
  #   - apt update && apt -y install make autoconf
  script:
    - cmake -DSDQUADX_BUILD_TESTS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -H$CI_PROJECT_DIR -B$CMAKE_BUILD
    - cmake --build $CMAKE_BUILD --target all

# run tests using the binary built before
test:
  stage: test
  script:
    - cpplint --quiet --recursive $CI_PROJECT_DIR/source
    - cppcheck --std=c++17 --quiet --enable=performance,portability $CI_PROJECT_DIR/source
    - cd $CMAKE_BUILD && ctest
