name: test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install tools
        run: sudo apt install -y cppcheck
      - name: run clang-format
        run: |
          find ./include -name '*.h'  -print | xargs clang-format -n -Werror && \
          find ./source -name '*.h'  -print | xargs clang-format -n -Werror && \
          find ./source -name '*.cc'  -print | xargs clang-format -n -Werror
      - name: run cppcheck
        run: cppcheck --std=c++17 --quiet --enable=performance,portability ./source
  test:
    name: test-${{ matrix.cc }}
    runs-on: ubuntu-latest
    container: ghcr.io/sdustio/spotng:dev
    strategy:
      matrix:
        cc: [gcc, clang]
        include:
          - cc: gcc
            cxx: g++
          - cc: clang
            cxx: clang++
    env:
      # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
      BUILD_TYPE: Debug
      CMAKE_BUILD: ./build
      CCACHE_DIR: ./.cache
      CCACHE_COMPRESS: "true"
      CCACHE_COMPRESSLEVEL: "6"
      CCACHE_MAXSIZE: 600M
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: actions/cache@v3
      id: cache-cmake
      with:
        path: ${{env.CCACHE_DIR}}
        key: ${{ runner.os }}-${{ runner.arch }}-${{ matrix.cc }}-testbuild-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-${{ matrix.cc }}-testbuild-

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: |
        cmake -DSPOTNG_BUILD_TESTS:BOOL=TRUE -B ${{env.CMAKE_BUILD}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
          -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
          "-DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake"

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{env.CMAKE_BUILD}} --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{env.CMAKE_BUILD}}
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Test Memory Check
      working-directory: ${{env.CMAKE_BUILD}}
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: |
        ctest -C ${{env.BUILD_TYPE}} -T memcheck
